version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: vs_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: vs_frontend
    ports:
      - "80:80"
    volumes:
      - ./client:/app